# theme: jekyll-theme-minimal
remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
- Intro to Tapis:
  - Intro to Tapis: ./Intro_Tapis/01-intro-to-tapis
- Intro to Jupyter:
  - Introduction to Jupyter: ./Jupyter_Notebook/intro-to-jupyter
- Tapis Systems:
  - Intro to Tapis Systems: ./Tapis_systems/02-systems
- Natural Language Processing:
  - NLP: ./NLP/nlp
- Tapis Apps:
  - Intro to Apps: ./Tapis_apps_jobs/03-apps.md
- Tapis Jobs:
  - Intro to Tapis Jobs: ./Tapis_apps_jobs/04-jobs.md
- Jupyter Notebook:
  - Notebook: ./Jupyter_Notebook/TACCSTER23_sentiment_analysis.ipynb
 

theme: jekyll-theme-minimal
